prometheus:
  server:
    fullnameOverride: prometheus-server
    service:
      servicePort: 9090
  prometheus-node-exporter:
    fullnameOverride: prometheus-node-exporter
    hostRootFsMount:
      enabled: false
  prometheus-pushgateway:
    fullnameOverride: prometheus-pushgateway
  alertmanager:
    fullnameOverride: prometheus-alertmanager
  kube-state-metrics:
    fullnameOverride: prometheus-kube-state-metrics
