global:
  influxdb:
    url: http://influxdb.monitoring-stack.svc.cluster.local:8181
    database: grafana

  postgresql:
    host: postgresql.monitoring-stack.svc.cluster.local
    database: grafana
    user: grafana
    password: grafana-secret

# Subchart values can be set here and will override their defaults.
grafana:
  fullnameOverride: grafana
  adminUser: admin
  adminPassword: test123

  env:
    GF_DATABASE_TYPE: postgres
    GF_DATABASE_HOST: postgresql.monitoring-stack.svc.cluster.local
    GF_DATABASE_NAME: grafana
    GF_DATABASE_USER: grafana
    GF_DATABASE_PASSWORD: grafana-secret

  ingress:
    enabled: true
    hosts:
      - grafana.local

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: InfluxDB
          type: influxdb
          access: proxy
          url: http://influxdb.monitoring-stack.svc.cluster.local:8181
        - name: PostgreSQL
          type: postgres
          access: proxy
          url: postgresql.monitoring-stack.svc.cluster.local:5432
          database: grafana
          user: grafana
          password: grafana-secret

  database:
    host: postgresql.monitoring-stack.svc.cluster.local
    name: grafana
    user: grafana
    password: grafana-secret
  
  persistance:
    enabled: true

influxdb:
  database:
    create: true
    name: grafana

postgresql:
  auth:
    database: grafana
    username: grafana
    password: grafana-secret
