grafana:
  fullnameOverride: grafana
  adminUser: admin
  adminPassword: test123
  initChownData:
    enabled: false
  sidecar:
    dashboards:
      enabled: true
      provider:
        name: default

  replicas: 3

  env:
    GF_DATABASE_TYPE: postgres
    GF_DATABASE_HOST: postgresql.monitoring.svc.cluster.local
    GF_DATABASE_NAME: grafana
    GF_DATABASE_USER: grafana
    GF_DATABASE_PASSWORD: grafana-secret

  ingress:
    enabled: true
    hosts:
      - grafana.cluster.local

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: InfluxDB
          type: influxdb
          access: proxy
          url: http://influxdb.monitoring.svc.cluster.local:8181
        - name: PostgreSQL
          type: postgres
          access: proxy
          url: postgresql.monitoring.svc.cluster.local:5432
          database: grafana
          user: grafana
          password: grafana-secret
        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://prometheus-server.monitoring.svc.cluster.local:9090

  dashboards:
    default:
      kube-state-metrics:
        gnetId: 21742
        revision: 1
        datasource: Prometheus

  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: default
          orgId: 1
          folder: ""
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default

  database:
    host: postgresql.monitoring.svc.cluster.local
    name: grafana
    user: grafana
    password: grafana-secret
  
  persistence:
    enabled: true
