apiVersion: v2
name: tempo
description: Grafana Tempo distributed tracing backend
type: application
version: 0.1.0
appVersion: "2.3.1"

dependencies:
  - name: tempo-distributed
    version: 1.7.4
    repository: https://grafana.github.io/helm-charts
