tempo-distributed:
  fullnameOverride: tempo
  
  traces:
    otlp:
      grpc:
        enabled: true
      http:
        enabled: true
    zipkin:
      enabled: true
    jaeger:
      thriftHttp:
        enabled: true
    opencensus:
      enabled: true

  storage:
    trace:
      backend: local
      local:
        path: /var/tempo/traces
  
  persistence:
    enabled: true
    size: 10Gi

  serviceMonitor:
    enabled: true

  ingester:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution: []

  distributor:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution: []

  compactor:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi

  querier:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution: []

  queryFrontend:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi
    query:
      enabled: false

  gateway:
    enabled: true
    replicas: 1
    ingress:
      enabled: true
      hosts:
        - host: tempo.cluster.local
          paths:
            - path: /
              pathType: Prefix
