{{- if .Values.clusterSecretStore.enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-cluster-secretstore
  labels:
    {{- include "vault-secretstore.labels" . | nindent 4 }}
spec:
  provider:
    vault:
      server: {{ .Values.vault.server | quote }}
      path: {{ .Values.vault.path | quote }}
      version: v{{ .Values.vault.version }}
      {{- if .Values.vault.namespace }}
      namespace: {{ .Values.vault.namespace | quote }}
      {{- end }}
      auth:
        tokenSecretRef:
          name: {{ .Values.vault.auth.tokenSecretRef.name | quote }}
          key: {{ .Values.vault.auth.tokenSecretRef.key | quote }}
          namespace: {{ .Values.vault.auth.tokenSecretRef.namespace | quote }}
{{- end }}
