{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "influxdb3.serviceAccountName" . }}
  namespace: {{ include "influxdb3.namespace" . }}
  labels:
{{ include "influxdb3.labels" . | indent 4 }}
{{- end -}}
