apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-keys
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    # Reuse the same SecretStore!
    name: vault-cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: api-keys-secret
    creationPolicy: Owner
  data:
    - secretKey: stripe_api_key
      remoteRef:
        key: api/stripe
        property: api_key
    - secretKey: sendgrid_api_key
      remoteRef:
        key: api/sendgrid
        property: api_key
    - secretKey: slack_webhook
      remoteRef:
        key: api/slack
        property: webhook_url
