apiVersion: v2
name: grafana
description: Grafana Helm chart wrapper
type: application
version: 1.0.0
appVersion: "10.5.15"
dependencies:
  - name: grafana
    version: "10.5.15"
    repository: "https://grafana.github.io/helm-charts"
