apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-git-credentials
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://bitbucket.org/storelogix/kubernetes-demo.git
    targetRevision: main
    path: kubernetes/manifests/argocd-git-credentials
    helm:
      releaseName: argocd-git-credentials
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
