{{- if and .Values.enabled (eq .Values.source "vault") }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-git-credentials
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "argocd-git-credentials.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.vault.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.vault.secretStore.name }}
    kind: {{ .Values.vault.secretStore.kind }}
  target:
    name: git-repository-credentials
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      type: Opaque
      data:
        type: "git"
        url: {{ `"{{ .url }}"` }}
        {{- if eq .Values.repository.auth.type "ssh" }}
        sshPrivateKey: {{ `"{{ .sshPrivateKey }}"` }}
        insecureIgnoreHostKey: {{ .Values.repository.auth.insecureIgnoreHostKey | quote }}
        {{- if .Values.vault.includeKnownHosts }}
        sshKnownHosts: {{ `"{{ .sshKnownHosts }}"` }}
        {{- end }}
        {{- else }}
        username: {{ `"{{ .username }}"` }}
        password: {{ `"{{ .password }}"` }}
        {{- end }}
  data:
    - secretKey: url
      remoteRef:
        key: {{ .Values.vault.path }}
        property: url
    {{- if eq .Values.repository.auth.type "ssh" }}
    - secretKey: sshPrivateKey
      remoteRef:
        key: {{ .Values.vault.path }}
        property: sshPrivateKey
    {{- if .Values.vault.includeKnownHosts }}
    - secretKey: sshKnownHosts
      remoteRef:
        key: {{ .Values.vault.path }}
        property: sshKnownHosts
    {{- end }}
    {{- else }}
    - secretKey: username
      remoteRef:
        key: {{ .Values.vault.path }}
        property: username
    - secretKey: password
      remoteRef:
        key: {{ .Values.vault.path }}
        property: password
    {{- end }}
{{- end }}
