{{- if and .Values.enabled (eq .Values.source "direct") }}
apiVersion: v1
kind: Secret
metadata:
  name: git-repository-credentials
  namespace: {{ .Values.namespace }}
  labels:
    argocd.argoproj.io/secret-type: repository
    {{- include "argocd-git-credentials.labels" . | nindent 4 }}
type: Opaque
stringData:
  type: git
  url: {{ .Values.repository.url | quote }}
  {{- if eq .Values.repository.auth.type "ssh" }}
  sshPrivateKey: {{ .Values.repository.auth.sshPrivateKey | quote }}
  insecureIgnoreHostKey: {{ .Values.repository.auth.insecureIgnoreHostKey | quote }}
  {{- if .Values.repository.auth.sshKnownHosts }}
  sshKnownHosts: {{ .Values.repository.auth.sshKnownHosts | quote }}
  {{- end }}
  {{- else }}
  username: {{ .Values.repository.auth.username | quote }}
  password: {{ .Values.repository.auth.token | quote }}
  {{- end }}
{{- end }}
